type WorldBookActionError = {
  message: string;
  code: string;
};

export const WORLDBOOK_COPY = {
  exportJson: "导出 JSON",
  exporting: "导出中...",
  importJson: "导入 JSON",
  exportSuccess: "已导出 JSON",
  exportFailed: "导出失败",

  autoUpdateTitle: "世界书自动更新",
  autoUpdateHint: "章节定稿后会后台抽取并合并条目；失败不影响写作，可重试。",
  autoUpdateRefresh: "刷新状态",
  autoUpdateRetry: "重试",
  autoUpdateTrigger: "手动触发",
  autoUpdateProcessing: "处理中...",
  autoUpdateTriggeredToast: "已触发世界书自动更新（后台任务）",
  autoUpdateRetryToast: "已提交重试",
  autoUpdateTriggerFailed: "触发失败",
  autoUpdateRetryFailed: "重试失败",
  autoUpdateTargetChapter: "将补跑：",
  autoUpdateNoDoneChapter: "暂无已完成章节，世界书自动更新需要章节正文；请先完成章节或在章节页面触发",
  autoUpdateEmpty: "暂无任务记录（章节定稿后会自动创建）。",
  autoUpdateTaskCenter: "任务中心",
  autoUpdateRequestId: "request_id:",
  autoUpdateChapterId: "chapter_id:",
  autoUpdateRunId: "run_id:",
  autoUpdateApplied: "应用结果:",
  autoUpdateFailedFallback: "任务失败",

  searchLabel: "搜索（标题 / 关键词）",
  searchPlaceholder: "dragon",
  sortLabel: "排序",
  sortOptions: [
    { value: "updated_desc", label: "更新时间（updated_at）↓" },
    { value: "updated_asc", label: "更新时间（updated_at）↑" },
    { value: "priority_desc", label: "优先级（priority）↓" },
    { value: "priority_asc", label: "优先级（priority）↑" },
    { value: "enabled_desc", label: "启用（enabled）↓" },
    { value: "enabled_asc", label: "启用（enabled）↑" },
  ] as const,
  priorityOptions: [
    { value: "must", label: "必须（must）" },
    { value: "important", label: "重要（important）" },
    { value: "optional", label: "可选（optional）" },
    { value: "drop_first", label: "优先丢弃（drop_first）" },
  ] as const,
  pinyinTag: "拼音",
  paginationInfoPrefix: "已显示 ",
  paginationInfoMiddle: " 条（超过 ",
  paginationInfoSuffix: " 条时分页渲染）",
  paginationPagePrefix: "第 ",
  paginationPageSeparator: "/",
  paginationPageSuffix: " 页",
  paginationPrev: "上一页",
  paginationNext: "下一页",
  hiddenSelectionPrefix: "（含 ",
  hiddenSelectionSuffix: " 个未显示）",

  bulkConfirmText: "确认",
  bulkUpdatedToast: "已批量更新",
  bulkDeletedToast: "已批量删除",
  bulkUpdateFailed: "批量更新失败",
  bulkDeleteFailed: "批量删除失败",
  duplicateConfirmText: "复制",
  duplicateFailed: "复制失败",
  duplicateFailedEmpty: "复制失败：返回为空",
  duplicateSuccess: "已复制并进入编辑",
  duplicateRequiresSingle: "复制并编辑需要选择 1 条条目",

  importDrawerTitle: "世界书导入",
  importDrawerHint: "上传导出的整套 JSON（export_all），支持 dry_run 预演查看冲突并确认应用。",
  importFileTitle: "导入文件",
  importFileLabel: "导入 JSON 文件",
  importModeLabel: "导入模式",
  importModeMerge: "merge（按 title 创建/更新）",
  importModeOverwrite: "overwrite（先删除全部再导入）",
  importModeHint: "merge：同名 title 直接更新；overwrite：先删后导入（危险，需二次确认）。",
  importSelectedPrefix: "已选择: ",
  importSchemaVersionLabel: "schema_version:",
  importEntriesLabel: "entries:",
  importDryRunButton: "dry_run 预览",
  importApplyButton: "应用导入",
  importProcessing: "处理中...",
  importApplying: "导入中...",
  importLoadedToast: "已加载导入文件",
  importParseFailed: "导入 JSON 解析失败",
  importChooseFile: "请先选择导入 JSON 文件",
  importFailed: "导入失败",
  importOverwriteConfirmTitle: "确认覆盖导入？",
  importOverwriteConfirmDescription: "overwrite 会先删除当前所有条目，然后导入 JSON。",
  importOverwriteConfirmText: "继续",
  importOverwriteCancelText: "取消",
  importDryRunDone: "dry_run 完成",
  importDone: "导入完成",
  importPostApplyWarning: "WorldBook 已变更，建议到 RagPage 重新 build 知识库索引。",
  importReportTitle: "导入报告",
  importReportExplain: "字段解释：dry_run=预演（不写入）；mode=merge 合并更新 / overwrite 覆盖导入。",
  importReportCountsExplain: "created 新建 | updated 更新 | deleted 删除 | skipped 跳过",
  importReportConflicts: "冲突（conflicts）",
  importReportActions: "变更（actions）",
} as const;

export function formatWorldBookActionError(action: string, error: WorldBookActionError, options?: { count?: number }) {
  const countPrefix =
    typeof options?.count === "number" && Number.isFinite(options.count) ? `（${options.count}条）` : "";
  return `${action}${countPrefix}：${error.message} (${error.code})`;
}
