export const UI_COPY = {
  common: {
    loading: "加载中...",
    droppedParamsPrefix: "参数已自动降级：",
    copy: "复制",
    requestIdLabel: "请求 ID（request_id）",
  },
  brand: {
    appName: "ainovel Atelier",
  },
  nav: {
    home: "首页",
    groupWorkbench: "项目工作台",
    groupView: "查看",
    groupAiConfig: "项目配置",
    groupAdvancedDebug: "高级调试",
    groupAdmin: "管理",

    wizard: "开工向导",
    projectSettings: "项目设置",
    characters: "角色卡",
    outline: "大纲",
    writing: "写作",
    tasks: "任务中心",
    structuredMemory: "图谱底座数据",
    numericTables: "数值表格（NumericTables）",
    chapterAnalysis: "剧情记忆",
    preview: "预览",
    reader: "阅读",
    export: "导出",

    worldBook: "世界书",
    rag: "知识库（RAG）",
    search: "搜索引擎",
    graph: "图谱/关系",
    fractal: "分形（Fractal）",
    styles: "风格",
    prompts: "模型配置",
    promptStudio: "提示词工作室",
    promptTemplates: "提示词模板",
    foreshadows: "伏笔",
    dataImport: "导入",
    adminUsers: "用户管理",
    accountSecurity: "账户安全",
    notificationSettings: "通知设置",
    help: "术语/帮助",

    navMenu: "导航菜单",
    openNav: "打开导航",
    closeNav: "关闭导航",
    advancedDebugToggle: "显示高级调试（仅用于排障）",
    chooseProjectHint: "请选择一个项目以进入编辑页。",
    currentProject: "当前项目",
    backToHome: "返回首页",
  },
  notFound: {
    title: "页面不存在",
    description: "我们找不到你要访问的地址。你可以尝试以下入口：",
  },
  help: {
    title: "术语/帮助",
    subtitle: "常用术语速查 + 页面说明模板（何时用 / 风险 / 示例）。",
    termsTitle: "常用术语（速查）",
    terms: [
      { label: "提示词（prompt）", description: "给模型的指令文本；一般由“目标 + 约束 + 输入/输出格式”组成。" },
      { label: "向量化（embedding）", description: "把文本变成向量以便检索；需配置模型/接口，可能有成本与耗时。" },
      { label: "重排（rerank）", description: "对候选结果二次排序，提高命中质量；通常会增加一次额外计算。" },
      { label: "检索增强生成（RAG）", description: "先检索相关片段，再把片段注入生成上下文；用于增强一致性与引用。" },
      { label: "知识库（KB）", description: "RAG 的数据分组与权重配置单位；可按用途拆分并单独启用/排序。" },
      { label: "请求 ID（request_id）", description: "后端为一次请求生成的定位标识；遇到报错/异常优先记录它。" },
      { label: "JSON", description: "结构化数据格式；在高级调试/导入导出时常见。" },
    ],
    tipsTitle: "排障小贴士",
    tips: [
      "遇到报错：先记录 请求 ID（request_id）与复现步骤（点了什么/输入了什么）。",
      "遇到“加载慢/不稳定”：先看是否需要重建索引/入库，以及是否有大量数据导致分页/渲染压力。",
    ],
  },
  search: {
    title: "搜索引擎",
    subtitle: "VSCode 式全项目搜索（多源聚合，可筛选与跳转；替代旧“术语表/术语映射”入口）",
    queryPlaceholder: "输入关键词…",
    search: "搜索",
    clear: "清空",
    sourcesTitle: "来源",
    sourceLabels: {
      chapter: "章节",
      outline: "大纲",
      worldbookEntry: "世界书",
      character: "角色",
      storyMemory: "剧情记忆",
      sourceDocument: "导入文档",
      projectTableRow: "数值表格",
      memoryEntity: "图谱实体",
      memoryRelation: "人物关系",
      memoryEvidence: "关系证据",
    },
    emptyHint: "暂无结果",
    loadMore: "加载更多",
    jump: "跳转",
    jumpDisabledHint: "该来源暂不支持跳转（可复制 ID 后手动定位）",
    copyId: "复制 ID",
    copyIdFailTitle: "复制失败：请手动复制",
    copiedId: "已复制 ID",
    copyLocator: "复制 locator",
    copyLocatorFailTitle: "复制失败：请手动复制 locator",
    copiedLocator: "已复制 locator",
    copyFailedToast: "自动复制失败：已打开手动复制弹窗。",
    debugTitle: "Debug",
  },
  chapterAnalysis: {
    introTitle: "用途说明",
    introLine1: "将“剧情记忆标注”高亮映射回正文，便于核对与定位；点击高亮或右侧列表可跳转到对应片段。",
    introLine2: "注意：这里管理的是剧情记忆（Hook/伏笔/情节/摘要），不等于世界书设定（人物/地点/物品）。",
    entryLine: "入口：写作页（选中章节）→ 右上角“标注回溯”（需要 chapterId）。",
    storyMemoryTitle: "剧情记忆（StoryMemory）",
    storyMemorySubtitle:
      "这里的条目用于回溯定位与检索，可在此手工新增/编辑/合并/完成标记/删除；自动更新（plot_auto_update）也只写入剧情记忆，不会改动世界书。",
  },
  vectorRag: {
    title: "向量检索（Vector RAG）",
    subtitle: "Embedding 用于把文本变成向量以便检索；Rerank 用于对候选结果二次排序提升命中（可能增加耗时/成本）。",
    apiKeyHint: "API Key（接口密钥）加密存储，仅回显 masked；留空可使用后端环境变量。",
    save: "保存 RAG 配置",
    dryRunTitle: "测试配置（dry-run）",
    backendEnvFallbackHint: "不确定怎么配时，可保持留空让后端从环境变量读取。",
    pendingClearSuffix: " | 将在保存时清除",
    rerankTitle: "Rerank（重排）",
    rerankConfigDetailsTitle: "Rerank 提供方配置",
    rerankProviderLabel: "Rerank 提供方（provider；项目覆盖；留空=使用后端环境变量）",
    rerankBaseUrlLabel: "Rerank 基础地址（base_url；项目覆盖；留空=使用后端环境变量）",
    rerankModelLabel: "Rerank 模型（model；项目覆盖；留空=使用后端环境变量）",
    rerankTimeoutLabel: "Rerank 超时（timeout_seconds；项目覆盖；留空=使用后端环境变量）",
    rerankHybridAlphaLabel: "Hybrid Alpha（0-1；留空=0）",
    rerankApiKeyLabel: "Rerank API Key（api_key；项目覆盖；留空不修改）",
    rerankClearApiKey: "清除项目级 Rerank API Key",
    rerankResetOverrides: "恢复使用后端环境变量（清除项目覆盖）",
    embeddingTitle: "Embedding（向量化）配置",
    embeddingClearApiKey: "清除项目级 API Key",
  },
  structuredMemory: {
    title: "图谱底座数据（StructuredMemory）",
    subtitle: "图谱底座数据表：实体 / 关系 / 事件 / 伏笔 / 证据（含人物关系编辑与回滚）。",
    usageHint: "何时用：排查“图谱抽取/增量更新/注入”是否写入底层表，或需要按关键词检索与导出操作（不是数值表格）。",
    exampleHint: "示例：在查询框输入人物名，再切换到“关系/证据”观察命中与数量变化。",
    bulkOpsHint: "批量操作会生成 Memory Update 的 ops JSON：复制后到 Memory Update 粘贴并 Apply 才会生效。",
    bulkOpsRisk: "风险：Apply 会直接修改记忆表；建议先确认选中范围，必要时先复制 JSON 备份。",
    tabs: {
      entities: "实体",
      relations: "关系",
      events: "事件",
      foreshadows: "伏笔",
      evidence: "证据",
    },
    includeDeleted: "包含已删除（include_deleted）",
    copyDeleteOps: "复制删除操作 JSON",
    copyResolvedOps: "复制标记已解决 JSON",
    deleteOpsLabel: "删除操作（delete ops）",
    resolvedOpsLabel: "标记已解决（resolved ops）",
  },
  auth: {
    noAccountHint: "没有账号？",
    goRegister: "去注册",
    haveAccountHint: "已有账号？",
    goLogin: "去登录",
    loginTitle: "登录",
    loginSubtitle: "使用本地账号登录（登录状态保存在浏览器 Cookie；数据在服务器数据库）",
    devFallbackHint: "已启用开发演示模式：无需登录也可进入应用。",
    devFallbackRiskHint: "重要：仅用于本地开发/演示。部署到公网时务必关闭 dev_fallback，以免绕过登录。",
    devFallbackNextStepHint: "如需权限/协作/多用户，请在下方使用账号登录。",
    continueInDevFallback: "继续进入应用",
    userIdLabel: "登录用户名",
    userIdPlaceholder: "例如：admin",
    passwordLabel: "密码",
    passwordPlaceholder: "请输入密码",
    confirmPasswordLabel: "确认密码",
    confirmPasswordPlaceholder: "请再次输入密码",
    passwordHint: "密码至少 8 位",
    reset: "清空",
    login: "登录",
    loggingIn: "登录中...",
    loginSuccess: "登录成功",
    loginFooterHint: "提示：登录状态保存在浏览器 Cookie；退出登录会清理本地登录状态。",
    registerTitle: "注册",
    registerSubtitle: "创建本地账号（账号密码）",
    register: "注册并登录",
    registering: "注册中...",
    registerSuccess: "注册成功",
    logout: "退出登录",
    sessionExpireAtPrefix: "会话到期：",
    devFallbackTag: "本地模式（DEV）",

    linuxdoLogin: "LinuxDo 一键登录/注册",
    linuxdoLoginFailedPrefix: "LinuxDo 登录失败：",
    linuxdoNotEnabledHint:
      "LinuxDo 登录未启用：请在后端环境变量中配置 LINUXDO_OIDC_CLIENT_ID / LINUXDO_OIDC_CLIENT_SECRET / LINUXDO_OIDC_REDIRECT_URI。",
    linuxdoCheckFailedPrefix: "无法检查 LinuxDo 配置：",
  },
  writing: {
    contextPreview: "上下文预览",
    contextPreviewTitle: "上下文预览",
    contextPreviewSubtitle: "MemoryContextPack / logs",
    contextPreviewRefresh: "刷新",
    contextPreviewClose: "关闭",
    contextPreviewLoadFailedTitle: "加载失败",
    contextPreviewMissingProjectId: "缺少 projectId",
    memoryInjectionToggle: "世界书注入",
    memoryInjectionHint:
      "启用后：生成时会把世界书/记忆等模块的结果注入到提示词；上下文预览也会显示触发条目与最终注入文本。",
    memoryInjectionDisabledPreview: "世界书注入已关闭。开启后可查看触发条目与 text_md。",
    worldbookSectionTitle: "世界书（WorldBook）",
    contextPreviewRawPack: "raw MemoryContextPack",
    memoryPackEmpty: "当前为空包（Phase 0 占位）。",
    memoryUpdateDrawer: {
      title: "记忆更新（Memory Update）",
      subtitle: "三步：提议 → 审核 → 应用（Propose/Review/Apply）",
      step1: "步骤 1：提议（Propose）",
      step2: "步骤 2：审核（Review）",
      step3: "步骤 3：应用（Apply）",
      step1Hint: "提议：生成一组“对结构化记忆的变更建议”，不会立即写入。",
      step2Hint: "审核：逐项选择要应用的变更；建议先看“变更前/变更后”。",
      step3Hint: "应用：把已接受项写入数据库；重复点击为幂等（不会重复写入）。",
      inputTitle: "输入（JSON，可选）",
      inputHint: "高级用法：支持 ops 数组，或包含 ops 字段的对象。",
      focusLabel: "关注点（可选）",
      focusPlaceholder: "例如：只更新角色关系 / 仅新增事件",
      jsonLabel: "变更指令（memory_update_json）",
      autoPropose: "一键生成提议（Auto Propose）",
      propose: "生成提议（Propose）",
      proposing: "生成中...",
      proposeFailed: "提议（Propose）失败",
      reviewTitle: "变更差异",
      accept: "接受",
      diffPreview: "差异预览",
      before: "变更前",
      after: "变更后",
      applyAccepted: "应用已接受项（Apply）",
      applying: "应用中...",
      applyFailed: "应用（Apply）失败",
      retryApply: "重试应用",
      applyResultTitle: "应用结果（Apply Result）",
      warnings: "警告",
      warningsZero: "警告：0",
      missingProposeHint: "请先在“步骤 1”生成提议（Propose）。",
    },
    foreshadowDrawer: {
      title: "伏笔面板",
      openCountLabel: "开放伏笔",
      openOnlyHint: "说明：这里仅展示未回收的伏笔；标记回收后会从列表移除。",
      hasMoreTag: "（has_more）",
      requestIdPrefix: "request_id:",
      refresh: "刷新",
      refreshing: "加载中...",
      filterLabel: "筛选",
      filterPlaceholder: "输入关键词（可多词，用空格分隔）",
      filterHint: "支持按标题/正文预览/章节 ID 过滤；多个关键词用空格分隔。",
      empty: "暂无开放伏笔。你可以先在“章节分析”里保存到记忆库，再回来查看。",
      noTitle: "（无标题）",
      metaChapterId: "章节",
      metaScore: "重要性",
      metaTimeline: "时间线",
      jumpChapter: "打开章节",
      annotatePage: "标注页",
      resolve: "标记回收",
      resolveConfirmTitle: "标记伏笔已回收？",
      resolveConfirmText: "标记回收",
      resolveCancelText: "取消",
      resolveDoneToast: "已标记回收",
      contentEmpty: "（空）",
    },
  },
  worldbook: {
    entriesCountPrefix: "共 ",
    entriesCountSuffix: " 条",
    refresh: "刷新",
    create: "新建条目",

    bulkMode: "批量模式",
    bulkModeHint: "批量模式下：点击条目=选择/取消；全选会选中当前过滤结果全部条目。",
    bulkSelectedPrefix: "已选 ",
    bulkSelectedSuffix: " 条",
    bulkSelectAll: "全选",
    bulkClearSelection: "清空选择",
    bulkEnable: "批量启用",
    bulkDisable: "批量停用",
    bulkPriority: "优先级（priority）",
    bulkCharLimit: "字符上限（char_limit）",
    bulkApply: "应用",
    bulkDelete: "批量删除",
    bulkDuplicateEdit: "复制并编辑",
    bulkNoSelection: "请先选择条目",

    bulkEnableTitle: "批量启用条目？",
    bulkEnableDescPrefix: "将启用 ",
    bulkEnableDescSuffix: " 条。",
    bulkDisableTitle: "批量停用条目？",
    bulkDisableDescPrefix: "将停用 ",
    bulkDisableDescSuffix: " 条。",
    bulkUpdateTitle: "批量更新条目？",
    bulkUpdateDescPrefix: "将更新 ",
    bulkUpdateDescSuffix: " 条。",
    bulkDeleteTitle: "批量删除条目？",
    bulkDeleteDescPrefix: "将删除 ",
    bulkDeleteDescSuffix: " 条，删除后无法恢复。",
    bulkDuplicateTitle: "复制条目？",
    bulkDuplicateDescPrefix: "将复制 ",
    bulkDuplicateDescSuffix: " 条并进入编辑。",

    entriesTitle: "条目列表",
    entriesHint:
      "关键词条目：命中关键词才会注入。常驻（constant）条目：始终注入、会占用预算，建议少量使用。条目很多时列表会分页渲染，点击“显示更多”继续加载。",
    empty: "暂无条目",

    tagEnabled: "启用",
    tagDisabled: "停用",
    tagBlue: "常驻",
    tagGreen: "关键词",
    tagPriorityPrefix: "priority:",
    tagCharLimitPrefix: "limit:",
    keywordsPrefix: "关键词：",
    keywordsNone: "无",

    previewTitle: "预览触发",
    previewHint: "输入一段 query_text，查看会触发哪些条目以及最终拼接的 text_md。",
    previewRun: "预览",
    previewQueryLabel: "query_text",
    previewIncludeConstant: "包含常驻（constant）",
    previewEnableRecursion: "允许递归",
    previewCharLimit: "拼接字符上限",
    previewRequiresSaveHint: "当前条目有未保存修改：预览基于已保存条目，请先保存后再预览。",
    previewUseInDrawerHint: "编辑抽屉打开时请在抽屉内使用预览触发。",
    previewFailed: "预览失败",
    previewTriggeredPrefix: "触发 ",
    previewTriggeredSuffix: " 条",
    previewTruncated: "已截断（超出上限）",
    previewTriggeredList: "触发条目",
    previewNoTriggered: "未触发任何条目",
    previewText: "text_md（最终注入文本）",
    previewTextEmpty: "（空）",

    drawerTitle: "编辑世界书条目",
    newEntryHint: "新条目",
    close: "关闭",
    cancel: "取消",

    formTitle: "标题",
    formEnabled: "启用",
    formConstant: "常驻（constant）",
    formExcludeRecursion: "排除递归",
    formPreventRecursion: "阻止递归",
    formKeywords: "关键词（每行一个）",
    formKeywordsHint: "用于触发匹配（仅非常驻条目生效）。",
    formCharLimit: "字符上限",
    formPriority: "优先级",
    formContent: "内容（Markdown）",

    save: "保存",
    saving: "保存中...",
    saved: "已保存",

    delete: "删除",
    deleted: "已删除",

    discardChangesTitle: "丢弃未保存修改？",
    discardChangesDesc: "关闭前将丢弃当前未保存的修改。",
    discardChangesConfirm: "丢弃",
    discardChangesCancel: "继续编辑",

    validationTitleRequired: "标题不能为空",

    deleteTitle: "删除该条目？",
    deleteDesc: "删除后无法恢复。",
    deleteConfirm: "删除",
    deleteCancel: "取消",

    missingProjectId: "缺少 projectId",
  },
  rag: {
    title: "Vector RAG 管理",
    subtitle: "状态 / 查询 / 入库 / 重建索引：用于排查“注入不生效/命中不稳定/索引过期”。",
    usageHint: "何时用：写作时感觉“世界书/上下文注入不生效”或检索结果不稳定时，先来这里看状态与命中。",
    exampleHint: "示例：输入章节片段或关键词（如“dragon”）点击“查询”，检查命中来源与注入结果。",
    riskHint: "风险：入库/重建可能耗时；若配置为在线模型，可能产生费用。",

    settings: "模型配置（Vector RAG）",
    ingest: "触发入库（Ingest）",
    rebuild: "重建索引（Rebuild）",
    rebuildNeedConfig: "重建索引（Rebuild，需配置）",
    rebuildRecommended: "重建索引（Rebuild，建议）",

    kbTitle: "知识库（KB）",
    kbOrderLabel: "排序（order）",
    kbEnabledLabel: "启用（enabled）",
    kbWeightLabel: "权重（weight）",
    kbNameLabel: "名称（name）",
    kbNewNameLabel: "新建知识库名称（name）",
    kbNewNamePlaceholder: "例如：我的知识库",

    sourcesTitle: "查询来源",
    queryTitle: "查询",
    injectionTitle: "注入结果",
    advancedDebugTitle: "高级调试",
    rerankTitle: "重排（Rerank）",

    ingestResultTitle: "入库结果（Ingest result）",
    rebuildResultTitle: "重建结果（Rebuild result）",
  },
  graph: {
    title: "图谱",
    subtitle: "图谱上下文（GraphContext）：查询命中实体 + 1-hop 关系 + 证据回放；支持跳转到人物关系编辑。",
    usageHint: "何时用：想确认“哪些实体/关系被识别并注入”，或从查询结果跳到人物关系编辑/证据定位。",
    exampleHint: "示例：把章节中的一句话粘贴到查询框，点击“查询”，查看命中实体与证据来源。",
    riskHint: "风险：该页为高级调试，会展示部分原始结果与证据片段；请避免在共享环境泄露项目内容。",

    enabledToggle: "启用（enabled）",
    queryTextLabel: "查询文本（query_text）",
    queryTextPlaceholder: "输入章节文本或关键片段（命中实体名/别名）",
    queryRun: "查询",

    autoUpdateTitle: "自动更新任务（graph_auto_update）",
    autoUpdateFocusLabel: "focus（可选）",
    autoUpdateFocusPlaceholder: "可选：本次希望聚焦的实体/关系/片段",
    autoUpdateCreateButton: "创建自动更新任务",
    autoUpdateCreatedToast: "已创建自动更新任务",
    autoUpdateMissingChapterId: "缺少 chapterId：请从写作页跳转或在 URL 添加 ?chapterId=<...>",
    autoUpdateLastTaskIdLabel: "last_task_id",
    autoUpdateOpenTaskCenter: "打开任务中心",
    autoUpdateCopyTaskId: "复制 task_id",

    overviewTitle: "结论摘要",
    injectionPreviewTitle: "注入预览（prompt_block.text_md）",
    nodesTitle: "节点",
    matchedLabel: "命中（matched）",
    relationsTitle: "关系",
    evidenceTitle: "证据（source_id 命中节点/边）",
    advancedDebugTitle: "高级调试（raw graph query result）",
  },
  promptStudio: {
    titleBeta: "提示词工作室（beta）",
    loadingA11y: "正在加载提示词工作室…",
    missingProjectId: "缺少 projectId",
    processing: "处理中…",

    previewNote: "预览通过后端渲染接口生成。",
    backToPrompts: "返回模型配置",
    newbiePromptTemplates: "新手：Prompt 模板",
    goWriting: "去写作",

    intro: "在这里管理预设与提示块，并生成后端渲染预览。",
    recommendedFlow: "推荐流程：模型配置 →（新手模板/工作室）→ 大纲生成 → 章节生成 → 记忆更新。",
    quickStart: "快速开始：选中预设 → 编辑模板片段 → 右侧预览 → 回到写作页点击“AI 生成”。",
    advancedHint: "提示：这里是高级模式；若你只想改“关键提示词”，建议从“新手：Prompt 模板”开始。",

    conceptTitle: "概念说明（预设/提示块/优先级）",

    enableRecommendedPresets: "一键启用推荐预设（大纲/章节）",

    toastRecommendedNotFound: "未找到推荐预设，请刷新后重试",
    toastRecommendedEnabled: "已启用推荐预设：大纲/章节",
    toastPresetSaved: "已保存预设",
    toastPresetDeleted: "已删除预设",
    toastBlockSaved: "已保存块",
    toastBlockDeleted: "已删除块",
    toastReordered: "已更新排序",

    confirmDeletePresetTitle: "删除预设？",
    confirmDeletePresetConfirm: "删除",
    confirmDeleteBlockTitle: "删除块？",
    confirmDeleteBlockConfirm: "删除",
    confirmDeleteBlockDescFallback: "将删除该提示块。",

    tasks: {
      outlineGenerate: "大纲（outline_generate）",
      chapterGenerate: "章节（chapter_generate）",
      planChapter: "规划（plan_chapter，M3）",
      postEdit: "润色（post_edit，M3）",
      contentOptimize: "正文优化（content_optimize，P0）",
      chapterAnalyze: "章节分析（chapter_analyze，P2）",
      chapterRewrite: "章节重写（chapter_rewrite，P2）",
    },
  },
  fractal: {
    title: "分形记忆（Fractal）",
    tag: "Fractal",
    subtitle: "用于查看/回放分形记忆注入文本，帮助排查记忆注入与摘要是否按预期工作。",
    usageHint: "何时用：写作中出现“记忆注入不生效/摘要异常/上下文不稳定”等问题时。",
    riskHint: "风险：该页为高级调试，会展示部分 prompt/内部状态；请避免在共享环境泄露项目内容。",
  },
  taskCenter: {
    title: "任务中心",
    subtitle: "查看记忆变更集与后台任务的状态、错误与排障信息。",
    usageHint: "何时用：生成/记忆更新后结果不符合预期，或需要查看后台任务是否失败/排队/运行中。",
    riskHint: "风险：该页包含较多排障字段（request_id/error 等）；对外分享时注意脱敏。",
  },
  featureDefaults: {
    ariaLabel: "默认行为（Feature Defaults）",
    title: "默认行为（默认开启）",
    subtitle: "普通用户默认开启记忆注入与后台自动更新；高级用户可按需关闭以节省成本/提升速度。",
    memoryInjectionLabel: "写作默认开启记忆注入（Memory Injection）",
    memoryInjectionHint:
      "关闭后：章节生成/上下文预览默认不注入世界书/记忆模块；仍可在写作页临时开启（建议用于成本控制/排障）。",
    reset: "恢复默认（开启）",
    resetHint: "仅对当前浏览器生效（localStorage；可随时切换）。",
    toastEnabled: "已开启：写作默认记忆注入",
    toastDisabled: "已关闭：写作默认记忆注入",
    toastReset: "已恢复默认：写作默认记忆注入（开启）",
    autoUpdateHint:
      "后台自动更新（世界书/图谱/向量/搜索）默认开启：章节定稿/内容变更后会静默调度任务；可在「任务中心」查看状态与重试。",
  },
} as const;
